"""empty message

Revision ID: 0fd14c27f828
Revises: 7a197383b8b7
Create Date: 2023-11-22 21:05:16.936402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fd14c27f828'
down_revision = '7a197383b8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_delivery', sa.DateTime(), nullable=True))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=True))
        batch_op.drop_column('name_profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_profile', mysql.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.drop_column('date_delivery')

    # ### end Alembic commands ###
