"""empty message

Revision ID: 210e7198640e
Revises: 38760f09f317
Create Date: 2023-12-22 09:31:03.001871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210e7198640e'
down_revision = '38760f09f317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prueba')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('cod_employes', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('gps_id', sa.VARCHAR(length=12, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('lastname_user', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('archivo', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('create_date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('cod_employe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cod_pc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_delivery', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cod_employe_id'], ['employes_state.cod_employe_state'], name='FK__prueba__cod_empl__02FC7413'),
    sa.ForeignKeyConstraint(['cod_pc_id'], ['pc.cod_pc'], name='FK__prueba__cod_pc_i__03F0984C'),
    sa.PrimaryKeyConstraint('cod_employes', name='PK__prueba__E6054D589C0701A5')
    )
    # ### end Alembic commands ###
