"""cambio usuario add rut

Revision ID: 7a197383b8b7
Revises: 
Create Date: 2023-11-17 10:10:59.731205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a197383b8b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pc_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rut_user', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pc_users', schema=None) as batch_op:
        batch_op.drop_column('rut_user')

    # ### end Alembic commands ###
