"""empty message

Revision ID: 866e107e3529
Revises: 0fd14c27f828
Create Date: 2023-11-23 09:59:37.044960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '866e107e3529'
down_revision = '0fd14c27f828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_log', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('archivo_log')

    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###
