"""empty message

Revision ID: a84e1a6c8fc4
Revises: 210e7198640e
Create Date: 2023-12-22 13:23:58.659237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84e1a6c8fc4'
down_revision = '210e7198640e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'state', ['cod_state_id'], ['cod_state'])

    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_cell_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_delivery_cell', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'cell', ['cod_cell_id'], ['cod_cell'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date_delivery_cell')
        batch_op.drop_column('cod_cell_id')

    with op.batch_alter_table('cell', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cod_state_id')

    # ### end Alembic commands ###
