"""empty message

Revision ID: da707bcdf890
Revises: e20e085c6ffa
Create Date: 2023-12-01 10:49:58.725999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da707bcdf890'
down_revision = 'e20e085c6ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_cod_employe', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('log_name_employe', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('log_name_employe')
        batch_op.drop_column('log_cod_employe')

    # ### end Alembic commands ###
