"""cambios en log

Revision ID: e20e085c6ffa
Revises: 81ef07e931d2
Create Date: 2023-11-30 11:04:48.314763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20e085c6ffa'
down_revision = '81ef07e931d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_pc_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('log_pc_nc', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('log_pc_st', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('log_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('log_state', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('log_archivo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('log_cod_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('FK__log__cod_pc_id__68487DD7', type_='foreignkey')
        batch_op.drop_constraint('FK__log__cod_user_id__6A30C649', type_='foreignkey')
        batch_op.drop_constraint('FK__log__cod_employe__693CA210', type_='foreignkey')
        batch_op.drop_column('archivo_log')
        batch_op.drop_column('state_log')
        batch_op.drop_column('cod_user_id')
        batch_op.drop_column('date_log')
        batch_op.drop_column('cod_employe_id')
        batch_op.drop_column('cod_pc_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_pc_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cod_employe_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_log', sa.DATETIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cod_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state_log', sa.VARCHAR(length=12, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('archivo_log', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK__log__cod_employe__693CA210', 'employes', ['cod_employe_id'], ['cod_employes'])
        batch_op.create_foreign_key('FK__log__cod_user_id__6A30C649', 'users', ['cod_user_id'], ['cod_user'])
        batch_op.create_foreign_key('FK__log__cod_pc_id__68487DD7', 'pc', ['cod_pc_id'], ['cod_pc'])
        batch_op.drop_column('log_cod_user_id')
        batch_op.drop_column('log_archivo')
        batch_op.drop_column('log_state')
        batch_op.drop_column('log_date')
        batch_op.drop_column('log_pc_st')
        batch_op.drop_column('log_pc_nc')
        batch_op.drop_column('log_pc_id')

    # ### end Alembic commands ###
